---
  server:
    applicationConnectors:
    - type: http
      port: 80
    adminConnectors:
    - type: http
      port: 8091

  jedis:
    host:
    port:
    password:

  lastFm:
    apiKey:
    secret:

  mappings:
    - input: g2015
      to: g2015
    - input: g2013
      to: glast2013
